Feat/ced 41
cedana/cedana pull request #86
Opened 2023-09-27 21:14 UTC by bsmithai

2023-09-29 21:11 UTC, avalonbits requested changes

2023-09-29 21:11 UTC, avalonbits commented on services/server/server.go
> +	url := os.Getenv("CHECKPOINT_SERVICE_URL") + "/checkpoint/6291dc64-289f-4744-9aa6-2a382b0a9a30/upload/" + uploadResp.UploadID
you need to add the /part/{part_number}  as well.

2023-10-09 12:54 UTC, nravic commented on api/server.go
> +		file, err := os.Open(s.Client.CheckpointDir + ".zip")
CheckpointDir should go and be replaced by queries to the db for the checkpoint, makes this interface a lot cleaner

2023-10-09 12:54 UTC, nravic commented on cmd/cli.go
> +			// ID:   args[1],
passing ID to startTask for args needs to come back - it's a simple way to attach a process to a jobID for an orchestrator

2023-10-12 14:35 UTC, nravic approved these changes
lgtm, will correct issues as they come up

2023-10-12 14:35 UTC, merged